
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import static com.mongodb.client.model.Filters.eq;
import java.util.ArrayList;
import java.util.Random;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author tv8392uu
 */
public class LoggedInPage extends javax.swing.JFrame {

    /**
     * Creates new form LoggedInPage
     */
    private String username;

    public LoggedInPage(String username) {
        this.username = username;
        initComponents();
        userNameLabel.setText(username + "'s Page");

        MongoConnection myMongo = new MongoConnection();
        MongoCollection<org.bson.Document> coll = myMongo.database.getCollection("Login");
        MongoCollection<org.bson.Document> videoReviewColl = myMongo.database.getCollection("VideoGameReview");
        MongoCollection<org.bson.Document> boardReviewColl = myMongo.database.getCollection("BoardGameReview");

        org.bson.Document user = coll.find(eq("username", username)).first();

        try {
            String userStats = "Total Reviews: ";
            userStats += user.get("totalReviews").toString() + "\n";
            userStats += "Liked Games: ";
            ArrayList<org.bson.Document> likedGames = (ArrayList<org.bson.Document>) user.get("likedGames");

            for (int i = 0; i < likedGames.size(); i++) {
                Object[] likedGame = likedGames.get(i).values().toArray();
                String likedGameString = likedGame[0].toString();
                likedGameString.replace('[', ' ');
                likedGameString = likedGameString.replace(']', ' ');
                userStats += likedGameString + "\n";
            }
            userInfoArea.setText(userStats);
        }
        catch(NullPointerException e) {
            userInfoArea.setText("Contribute to the forum to see your stats here!");
        }
        
        FindIterable<Document> videoReviews = videoReviewColl.find(eq("Reviewing User", username));
        FindIterable<Document> boardReviews = boardReviewColl.find(eq("Reviewing User", username));

        ArrayList<Document> reviewList = new ArrayList();

        for (Document doc : videoReviews) {
            reviewList.add(doc);

        }

        Random rand = new Random();
        Review hotReview = new Review();
        Document thisReview;
        String hotReviews = "Video Game Reviews:\n";
        for (int i = 0; i < reviewList.size(); i++) {
            thisReview = reviewList.get(i);
            hotReview.setGameName(thisReview.get("Game").toString());
            hotReview.setReview(thisReview.get("Review").toString());
            hotReview.setScore(thisReview.get("Score").toString());

            hotReviews += hotReview.toString() + "\n";
        }

        reviewList = new ArrayList();

        for (Document doc : boardReviews) {
            reviewList.add(doc);

        }

        hotReviews += "\n\nBoard Game Reviews: \n";
        for (int i = 0; i < reviewList.size(); i++) {
            thisReview = reviewList.get(i);
            hotReview.setGameName(thisReview.get("Game").toString());
            hotReview.setReview(thisReview.get("Review").toString());
            hotReview.setScore(thisReview.get("Score").toString());

            hotReviews += hotReview.toString() + "\n";
        }
        
        this.reviewArea.setText(hotReviews);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userNameLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userInfoArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        reviewArea = new javax.swing.JTextArea();
        reviewsLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userNameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        userNameLabel.setText("User");

        userInfoArea.setColumns(20);
        userInfoArea.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        userInfoArea.setRows(5);
        jScrollPane1.setViewportView(userInfoArea);

        reviewArea.setColumns(20);
        reviewArea.setRows(5);
        jScrollPane2.setViewportView(reviewArea);

        reviewsLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        reviewsLabel.setText("Your Reviews");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reviewsLabel)
                            .addComponent(backButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reviewsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainMenu(username).setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea reviewArea;
    private javax.swing.JLabel reviewsLabel;
    private javax.swing.JTextArea userInfoArea;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
