
import java.awt.EventQueue;

/**
 * Assignment: Final Project
 * Author: Brandon Salmon and PK Lai
 * Description: Main menu page
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    private String username;
    
    public MainMenu(String username) {
        initComponents();
        this.username = username;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        videoGameButton = new javax.swing.JButton();
        boardGameButton = new javax.swing.JButton();
        YourPageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Main Menu");

        videoGameButton.setText("Video Games");
        videoGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                videoGameButtonActionPerformed(evt);
            }
        });

        boardGameButton.setText("Board Games");
        boardGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boardGameButtonActionPerformed(evt);
            }
        });

        YourPageButton.setText("Your Page");
        YourPageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YourPageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(videoGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addComponent(boardGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addComponent(YourPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(videoGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boardGameButton, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(YourPageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //go to video game board
    private void videoGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_videoGameButtonActionPerformed
        // TODO add your handling code here:
        EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                try {
                                    VideoGamePage window = new VideoGamePage(username);
                                    window.setVisible(true);
                                    MainMenu.super.dispose();
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                            }

                        });
    }//GEN-LAST:event_videoGameButtonActionPerformed

    //go to board game board
    private void boardGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boardGameButtonActionPerformed
        // TODO add your handling code here:
        EventQueue.invokeLater(new Runnable() {
                            public void run() {
                                try {
                                    BoardGamePage window = new BoardGamePage(username);
                                    window.setVisible(true);
                                    MainMenu.super.dispose();
                                } catch (Exception e) {
                                    e.printStackTrace();
                                }
                            }

                        });
    }//GEN-LAST:event_boardGameButtonActionPerformed

    //go to your page
    private void YourPageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YourPageButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new LoggedInPage(username).setVisible(true);
    }//GEN-LAST:event_YourPageButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton YourPageButton;
    private javax.swing.JButton boardGameButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton videoGameButton;
    // End of variables declaration//GEN-END:variables
}
